<a href="https://colab.research.google.com/github/leenasilvoster/LLM/blob/main/Embedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Word Embedding Techniques using Embeddding Layer in Keras

In [ ]:
!pip install tensorflow-gpu

  Using cached tensorflow-gpu-2.12.0.tar.gz (2.6 kB)
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


In [ ]:
from tensorflow.keras.preprocessing.text import one_hot

In [ ]:
sent = ['the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'I am a good developer',
        'understand the meaning of words',
        'your videos are good']

In [ ]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [ ]:
###Vocabulary size
voc_size =500

One Hot Representation

In [ ]:
onehot_repr =[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[185, 367, 393, 468], [185, 367, 393, 64], [185, 360, 393, 490], [166, 458, 478, 189, 85], [166, 458, 478, 189, 400], [42, 185, 439, 393, 280], [116, 6, 14, 189]]


Word Embedding Representation

In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [ ]:
#post-padding
sent_length = 5
embedded_docs= pad_sequences(onehot_repr,padding = 'post',maxlen = sent_length)
print(embedded_docs)

[[185 367 393 468   0]
 [185 367 393  64   0]
 [185 360 393 490   0]
 [166 458 478 189  85]
 [166 458 478 189 400]
 [ 42 185 439 393 280]
 [116   6  14 189   0]]


In [ ]:
#pre-padding
sent_length = 5
embedded_docs= pad_sequences(onehot_repr,padding = 'pre',maxlen = sent_length)
print(embedded_docs)

[[  0 185 367 393 468]
 [  0 185 367 393  64]
 [  0 185 360 393 490]
 [166 458 478 189  85]
 [166 458 478 189 400]
 [ 42 185 439 393 280]
 [  0 116   6  14 189]]


In [ ]:
dim = 10

In [ ]:
model = Sequential()
# Add Embedding layer
model.add(Embedding(input_dim=voc_size, output_dim=dim, input_length=sent_length))

model.compile('adam','mse')

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [ ]:
# Build the model by running some data through it (this step is important)
model.build(input_shape=(None, sent_length))

In [ ]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)              │ (None, 5, 10)               │           5,000 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 5,000 (19.53 KB)

 Trainable params: 5,000 (19.53 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
embedded_docs[0]

array([  0, 185, 367, 393, 468], dtype=int32)

In [ ]:
# Predict on the first sentence (single sentence needs to be reshaped to match the input shape)
prediction = model.predict(np.array([embedded_docs[0]]))  # Add extra dimension for batch size

# Print the prediction
print(prediction)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 240ms/step
[[[ 0.01870468  0.02114104  0.04491046 -0.02377381  0.02922643
   -0.02301782 -0.00410906  0.04709064 -0.01855329 -0.0218853 ]
  [-0.00206881 -0.01774021  0.02514711 -0.04630318 -0.04560481
    0.04299894 -0.00699171 -0.03395355  0.02143501  0.04079616]
  [ 0.00050136  0.03544197 -0.02328682  0.00050267  0.01450955
   -0.03066053  0.01234299  0.01208179  0.01845935 -0.03626735]
  [ 0.01072077  0.00154215  0.04319659 -0.03072939  0.04993636
   -0.03758941  0.01009126  0.04586451 -0.00473794  0.03320405]
  [-0.03573146 -0.03639203 -0.02474397 -0.03044442 -0.00095358
    0.04526765 -0.01364505  0.01762288  0.00025561  0.00568343]]]


In [ ]:
###Assignment
sent = ['The world is a better place',
        'Marvel series is my favourite movie',
        'I like DC movies',
        'the cat is eating the food',
        'Tom and Jerry is my favourite movie'.
        'Python is my favourite programming language'

]

In [ ]:
imdb